matrix:
  include:
    - os : linux
      language: python
      python: "3.7"
    - os : windows
      language : shell
      python: "3.7"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    elif  [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi

install:
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then
      bash miniconda.sh -b -p $HOME/miniconda;
      export PATH="$HOME/miniconda:$HOME/miniconda/bin:$PATH";
    elif  [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      choco install miniconda3 --params="'/AddToPath:1'";
      export PATH="/c/tools/miniconda3/scripts:/c/tools/miniconda3/:$PATH";
    fi
  - hash -r;
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - echo $TRAVIS_OS_NAME
  - echo $TRAVIS_PYTHON_VERSION
  - conda env create python=$TRAVIS_PYTHON_VERSION -f environment.yml;
  - source activate pybcli

script:
  - python -m unittest tests
