matrix:
  include:
    - os : linux
      language: python
      sudo: required
      dist: xenial
      python: "3.7"
      env:
        - UPX_PATH=$(PWD)/UPX
    - os : windows
      language : shell
      python: 3.7
      env:
        - PY=py
        - UPX_PATH=$(PWD)/UPX

before_install:
  - ./scripts/before_install.sh

install:
  - ./scripts/install.sh

script:
  - python -m unittest $(PWD)/tests
  - python pyinstaller.py
