services:
  - docker

jobs:
  include:
    - stage: Windows build
      os: windows
      language: shell
      python: 3.7
      env:
      - PY=py
      - UPX_PATH="$PWD"/UPX

deploy:
  provider: releases
  api_key:
    secure: PeGhFBjv5dGt5g3Kkt+5k+Z147+zwpRokYYazjKRSNsionRGTQIn23X4t3o4kGNlWwTpMxYp1Tx+dzv9h6F0rMHYe2dnZZ/celIUP/0SIC83jkV5gPx1rJmTXcyDsDGGBfDkRTPPu4SEfuRs9i8g+MqvrJWWKS9MWFESH758gTBlsosIV8oiWZZsBX3Q5XFKGKaUKKMjOJLsp8vopj2G6lLlNaTY67R+EtHBw+qASRphIg0m6373PVhfxK3BwwiP6/Af67Sjs+AepIFxkoKZY4GrmwHdB1IGuUQZ8znucAUnoH4YpTKzJfb0WmKFx2EjTw9Qs4iGiuWvVsmHorcFhH5dLXhZLQM95Nc/YOWaEOQ8l1YeNFU82Xo5uUE96EPi9YLtCrHSLw0vOxc/SZr3ypbQt1ogtXkiGWPIdpfzP0THhgBcru2tl98gNIkvMxqxik5asXof/V9ocAcjLDP269sGSneJfTloen3we1qj6ojiZCaOm27sRl74Vk/60I7K6e4FRYoht7WGdsAlvwnOT17bN/XAZavjxkQxBnryzVYvtB2vTpLi5sFFCvT7+1z5mnzh2u92hwSiJBHSIwZzisQSCESjlW0VlV7ESuGaNf6CdDTjoLr1Wx7Jk15pnRUaJQdjzXG+kQCD/7GPzHLVzpqbHKW7twuSoJsD+K4fVVA=
  skip_cleanup: true
  file_glob: true
  file: dist/*
  draft: true
  on:
    tags: true
    repo: hallowf/py-backs-cli

before_install:
- ./scripts/win_before_install.sh
- docker build --platform linux -t hallowf/pybcli/lin -f Dockerfile .

install:
- "$PY -m pip install -r requirements.txt"
- docker run --platform linux -t -d --name pybcli_lin hallowf/pybcli/lin

script:
- $PY -m unittest discover tests/ "*_test.py"
- "$PY pyinstaller.py"
- docker cp --platform linux pybcli_lin:/code/dist/. dist/.
