matrix:
  include:
    - os : linux
      language: python
      sudo: required
      dist: xenial
      python: "3.7"
      env:
        - PY=python3
        - UPX_PATH="$PWD"/UPX
    - os : windows
      language : shell
      python: 3.7
      env:
        - PY=py
        - UPX_PATH=$(PWD)/UPX

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      ./scripts/osx_before_install.sh;
    elif [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      ./scripts/win_before_install.sh;
    fi

install:
  - ls
  - $PY -m pip install -r requirements.txt

script:
  - $PY -m unittest discover tests/ "*_test.py"
  - $PY pyinstaller.py
