jobs:
  include:
    - stage: Linux build
      language: python
      os: linux
      sudo: required
      dist: xenial
      python: '3.7'
      env:
      - PY=python3
      - UPX_PATH="$PWD"/UPX
    - stage: Windows build
      os: windows
      language: shell
      python: 3.7
      env:
      - PY=py
      - UPX_PATH="$PWD"/UPX
    - stage: Github Release
      deploy:
        before_install: echo skipping
        install: echo skipping
        script: echo skipping
        provider: releases
        api_key:
          secure: PeGhFBjv5dGt5g3Kkt+5k+Z147+zwpRokYYazjKRSNsionRGTQIn23X4t3o4kGNlWwTpMxYp1Tx+dzv9h6F0rMHYe2dnZZ/celIUP/0SIC83jkV5gPx1rJmTXcyDsDGGBfDkRTPPu4SEfuRs9i8g+MqvrJWWKS9MWFESH758gTBlsosIV8oiWZZsBX3Q5XFKGKaUKKMjOJLsp8vopj2G6lLlNaTY67R+EtHBw+qASRphIg0m6373PVhfxK3BwwiP6/Af67Sjs+AepIFxkoKZY4GrmwHdB1IGuUQZ8znucAUnoH4YpTKzJfb0WmKFx2EjTw9Qs4iGiuWvVsmHorcFhH5dLXhZLQM95Nc/YOWaEOQ8l1YeNFU82Xo5uUE96EPi9YLtCrHSLw0vOxc/SZr3ypbQt1ogtXkiGWPIdpfzP0THhgBcru2tl98gNIkvMxqxik5asXof/V9ocAcjLDP269sGSneJfTloen3we1qj6ojiZCaOm27sRl74Vk/60I7K6e4FRYoht7WGdsAlvwnOT17bN/XAZavjxkQxBnryzVYvtB2vTpLi5sFFCvT7+1z5mnzh2u92hwSiJBHSIwZzisQSCESjlW0VlV7ESuGaNf6CdDTjoLr1Wx7Jk15pnRUaJQdjzXG+kQCD/7GPzHLVzpqbHKW7twuSoJsD+K4fVVA=
        skip_cleanup: true
        file_glob: true
        file: bdist/*
        draft: true
        on:
          repo: hallowf/py-backs-cli

before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    ./scripts/osx_before_install.sh;
  elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    ./scripts/lin_before_install.sh;
  elif [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
    ./scripts/win_before_install.sh;
  fi

install:
- "$PY -m pip install -r requirements.txt"

script:
- $PY -m unittest discover tests/ "*_test.py"
- "$PY pyinstaller.py"
